apiVersion: v1
kind: Service
metadata:
  name: java-backend
spec:
  type: NodePort
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      name: http-traffic
      port: 5001
      targetPort: 5001
      nodePort: 30080

  